import json
import logging
import os
import pickle
from shutil import SameFileError
from typing import BinaryIO, List, Optional

import numpy as np
import torch
from fsspec.core import url_to_fs
from lightning.fabric.utilities.types import _PATH
from pyarrow import fs as pyarrow_fs

from src.utils.decorators import retry


@retry()
def get_file_size(file_path: str) -> int:
    fs, _ = url_to_fs(file_path)
    return fs.size(file_path)


@retry()
def copy_to_remote(local_path: str, remote_path: str, recursive: bool = True) -> None:
    try:
        logging.info(f"Copying {local_path} to {remote_path}")
        fs, _ = url_to_fs(remote_path)
        fs.put(local_path, remote_path, recursive=recursive)
        logging.info(f"Finished copying {local_path} to {remote_path}")
    except SameFileError:
        logging.warning(f"{local_path} and {remote_path} are the same. Skipping copy.")


@retry()
def file_exists_local_or_remote(file_path: str) -> bool:
    fs, _ = url_to_fs(file_path)
    return fs.exists(file_path)


@retry()
def open_local_or_remote(file_path: str, mode: str = "r") -> BinaryIO:
    fs, _ = url_to_fs(file_path)
    return fs.open(file_path, mode)


def load_json(file_path: str) -> dict:
    with open_local_or_remote(file_path, "r") as f:
        feature_map = json.load(f)
    return feature_map


@retry()
def open_pyarrow_file(file_path: str):
    # Optimized function for large pyarrow files (ie. parquet)
    # enable us to read row groups instead of entire file.
    fs, path = pyarrow_fs.FileSystem.from_uri(file_path)
    return fs.open_input_file(path)


def get_last_modified_file(
    folder_path: str, suffix="*", should_update_prefix=True
) -> str:
    """
    Can get the last modified file in a folder from a local or remote filesystem.
    """
    fs, _ = url_to_fs(folder_path)
    file_list = list_files(folder_path, suffix, should_update_prefix)
    if not file_list:
        return ""

    latest_mtime = 0
    for file in file_list:
        info = fs.info(file)
        mtime = info.get("mtime", 0)
        if latest_mtime == 0 or mtime > latest_mtime:
            latest_mtime = mtime
            latest_file = file
    return latest_file


def remove_file_extension(path: _PATH) -> _PATH:
    """
    Removes the file extension from a given file path.

    Args:
        path (_PATH): The file path from which to remove the extension.

    Returns:
        _PATH: The file path without the extension.

    Example:
        >>> remove_file_extension("example/file.txt")
        'example/file'
    """
    base, _ = os.path.splitext(path)
    return base


def has_no_extension(filepath: _PATH) -> bool:
    # Extract just the filename from the path, handles both local and cloud paths
    filename = os.path.basename(filepath)
    # Split the filename and check if extension is empty
    _, extension = os.path.splitext(filename)
    return extension == ""


def list_subfolders(
    directory_path,
    should_update_prefix: bool = True,
):
    """
    List all folders inside a directory using fsspec.

    Args:
        directory_path (str): Path to the directory to search
                             (can be local or remote like 's3://', 'gs://', etc.)
        should_update_prefix (bool): If True, adds the prefix based on the filesystem,
                                     otherwise returns the path generated by glob
    Returns:
        list: List of folder paths
    """
    # Get the appropriate filesystem
    fs, _ = url_to_fs(directory_path)

    # List all items in the directory
    all_items = fs.ls(directory_path)

    # Filter to only include directories that are not the original one.
    folders = [
        f"{fs.protocol[0]}://{item}" if should_update_prefix else item
        for item in all_items
        if fs.isdir(item) and item != directory_path
    ]

    return folders


@retry()
def list_files(
    folder_path: str,
    suffix: str = "*",
    # if should_update_prefix is True, adds the prefix based on the filesystem,
    # otherwise returns the path generated by glob
    should_update_prefix: bool = True,
) -> List[str]:

    # We remove trailing slashes to avoid double slashes in the path
    folder_path = folder_path.removesuffix("/")

    fs, _ = url_to_fs(folder_path)
    return (
        # add the prefix for gcs.
        [f"{fs.protocol[0]}://{x}" for x in fs.glob(f"{folder_path}/{suffix}")]
        if should_update_prefix
        else fs.glob(f"{folder_path}/{suffix}")
    )


class IndexedEmbeddingLookup:
    """Compact embedding matrix with a sparse integer ID → row-index lookup.

    Supports item_id indexing without building a dense (max_id+1, d) tensor,
    which would be ~35 GB for this dataset.  The backing store is a np.memmap
    so the OS pages embeddings in on demand rather than loading all 23 GB.
    Items absent from the ID map return a zero vector.
    """

    def __init__(self, embeddings: np.ndarray, id_to_row: dict) -> None:
        self.embeddings = embeddings          # (N, embed_dim), may be a memmap
        self.id_to_row = id_to_row            # {int item_id: int row_idx}
        self._embed_dim = embeddings.shape[1]

    def __getitem__(self, item_id: int) -> torch.Tensor:
        row = self.id_to_row.get(int(item_id), None)
        if row is None:
            return torch.zeros(self._embed_dim, dtype=torch.float32)
        return torch.tensor(self.embeddings[row], dtype=torch.float32)

    def get_batch(self, item_ids) -> torch.Tensor:
        """Batch lookup via a single numpy fancy index — O(B) instead of O(B) Python calls.

        Returns a (B, embed_dim) float32 tensor. Missing IDs get zero vectors.
        """
        B = len(item_ids)
        rows = np.empty(B, dtype=np.intp)
        missing = []
        for i, iid in enumerate(item_ids):
            r = self.id_to_row.get(int(iid), -1)
            rows[i] = r
            if r < 0:
                missing.append(i)

        result = np.empty((B, self._embed_dim), dtype=np.float32)
        valid_mask = rows >= 0
        if valid_mask.any():
            result[valid_mask] = self.embeddings[rows[valid_mask]]
        if missing:
            result[missing] = 0.0
        return torch.from_numpy(result)


# Process-level cache so the same (embedding_path, id_map_path) pair is only
# loaded once.  Critical when text and image use the same file: without this,
# both maps allocate independent ~25 GB arrays and the job OOM-kills.
_embedding_cache: dict = {}


def load_indexed_npy_embeddings(
    embedding_path: str,
    id_map_path: str,
) -> "IndexedEmbeddingLookup":
    """Load a float32 embedding file paired with a .pkl item-ID list.

    Supports standard .npy files and raw float32 binary dumps (detected by
    the absence of the numpy magic bytes).  Returns an IndexedEmbeddingLookup
    that maps integer item IDs to float32 vectors on demand, avoiding the
    need to materialise a dense sparse-ID-indexed tensor.

    Calls with the same paths return the *same* object (process-level cache),
    so text and image embedding maps that point to the same file share one copy.

    Args:
        embedding_path: Path to a .npy file or raw float32 binary of shape (N, d).
        id_map_path: Path to a .pkl file containing either
            - a list  where list[row_idx] == item_id (str or int), or
            - a dict  where dict[item_id] == row_idx.
    """
    key = (embedding_path, id_map_path)
    if key in _embedding_cache:
        return _embedding_cache[key]

    with open(id_map_path, "rb") as f:
        id_map = pickle.load(f)

    if isinstance(id_map, dict):
        id_to_row = {int(k): int(v) for k, v in id_map.items()}
    else:
        id_to_row = {int(item_id): row_idx for row_idx, item_id in enumerate(id_map)}

    n_rows = len(id_to_row)

    # Detect format: standard .npy starts with b'\x93NUMPY'; anything else is
    # treated as a raw float32 binary dump (common for large embedding exports).
    with open(embedding_path, "rb") as f:
        magic = f.read(6)

    if magic[:6] == b"\x93NUMPY":
        # Use mmap so startup is instant even for 24+ GB files on slow Lustre.
        # The OS page cache warms up naturally over the first few thousand batches;
        # with 180 GB RAM the full 48 GB (text + image) fits in cache eventually.
        # Batch lookup (get_batch) is still O(1) C-level numpy gather — much
        # faster than the old per-item torch.tensor() calls regardless of mmap.
        try:
            embeddings = np.load(embedding_path, mmap_mode="r", allow_pickle=False)
            if embeddings.dtype != np.float32:
                # dtype conversion materialises the full array; unavoidable here.
                embeddings = np.array(embeddings, dtype=np.float32)
        except ValueError:
            embeddings = np.load(embedding_path, allow_pickle=True).astype(np.float32)
    else:
        total_floats = os.path.getsize(embedding_path) // 4
        embed_dim = total_floats // n_rows
        embeddings = np.memmap(
            embedding_path, dtype=np.float32, mode="r", shape=(n_rows, embed_dim)
        )

    result = IndexedEmbeddingLookup(embeddings, id_to_row)
    _embedding_cache[key] = result
    return result


def replace_char_after_segment(
    path: str,
    char_to_replace: str,
    replacement_char: str,
    segment_to_find: Optional[str] = None,
) -> str:
    """
    Replace a specific character with another character in a path string.
    If segment_to_find is provided, replacements occur only after that segment,
    or returns the original string if segment is not found.
    If segment_to_find is None, replacements occur throughout the entire string.

    Args:
        path (str): The full path string to process
        char_to_replace (str): The character to be replaced
        replacement_char (str): The character to use as replacement
        segment_to_find (Optional[str]): The path segment after which replacements
                                        should occur. If None, replace in the entire string.

    Returns:
        str: The modified path with character replacements.
            If segment_to_find is provided but not found, returns the original path unchanged.
    """
    # If no segment is specified, replace throughout the entire string
    if segment_to_find is None:
        return path.replace(char_to_replace, replacement_char)

    # Find the position of the segment in the path
    segment_index = path.find(segment_to_find)

    if segment_index != -1:
        # Include the full segment in the "before" part
        segment_end = segment_index + len(segment_to_find)
        before_segment = path[:segment_end]
        after_segment = path[segment_end:]

        # Replace characters only in the part after the segment
        modified_after_segment = after_segment.replace(
            char_to_replace, replacement_char
        )

        # Combine the parts
        return before_segment + modified_after_segment

    # If segment is not found, return the original path unchanged
    return path
